@echo off
set SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/maestriafinal
set SPRING_DATASOURCE_USERNAME=root
set SPRING_DATASOURCE_PASSWORD=root
set SPRING_SERVER_EGRESADOS_PORT=8084
set SPRING_JWT_KEY=SecretKey
set SPRING_JWT_EXPIRATION=86400000

mvn clean package
